"""
Django settings for NewsPaper project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fak!v+b$v*$qrk3mx79m%7ciakicq*ed2pp#7onjk*g63x5-_*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'NewsPaper.news',
    "django_filters",
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.yandex',
    'django_celery_beat',
]

# Добавить для allauth
SITE_ID = 1

# Настройки аутентификации
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/news/'
LOGOUT_REDIRECT_URL = '/news/'

# Настройки allauth
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
ACCOUNT_EMAIL_VERIFICATION = 'none'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ROOT_URLCONF = 'NewsPaper.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
                'NewsPaper.news.context_processors.categories_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'NewsPaper.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

LANGUAGES = [
    ('ru', 'Русский'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

SOCIALACCOUNT_PROVIDERS = {
    'yandex': {
        'APP': {
            'client_id': '8cc5de0fab584a428977b35eb340f70e',
            'secret': 'cccd22e988814e719d7d94b0890d6d96',
            'key': ''
        }
    }
}

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'mnhklee@yandex.ru'
EMAIL_HOST_PASSWORD = 'zjinpwsxpkurlige'  #пароль приложения
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Celery settings (для фоновых задач и еженедельной рассылки)
CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Расписание
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'weekly-digest': {
        'task': 'news.tasks.send_weekly_digest',
        'schedule': crontab(day_of_week='monday', hour=8, minute=0),
    },
}

SITE_URL = 'http://127.0.0.1:8000'

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'news-cache',
        'TIMEOUT': 300,  # 5 минут по умолчанию
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

CACHE_MIDDLEWARE_KEY_PREFIX = 'newsportal'

# Создаем директорию для логов, если её нет
LOG_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)


# Фильтр для проверки DEBUG режима
class RequireDebugTrue:
    """Фильтр: пропускает сообщения только когда DEBUG = True"""

    def __init__(self):
        from django.conf import settings
        self.debug = settings.DEBUG

    def filter(self, record):
        return self.debug


class RequireDebugFalse:
    """Фильтр: пропускает сообщения только когда DEBUG = False"""

    def __init__(self):
        from django.conf import settings
        self.debug = settings.DEBUG

    def filter(self, record):
        return not self.debug


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,

    # Форматтеры (определяем форматы вывода)
    'formatters': {
        # Для консоли (DEBUG и выше)
        'console': {
            'format': '{asctime} - {levelname} - {message}',
            'style': '{',
        },
        # Для консоли с доп. информацией (WARNING и выше)
        'console_warning': {
            'format': '{asctime} - {levelname} - {pathname} - {message}',
            'style': '{',
        },
        # Для general.log
        'general': {
            'format': '{asctime} - {levelname} - {module} - {message}',
            'style': '{',
        },
        # Для errors.log
        'error': {
            'format': '{asctime} - {levelname} - {pathname} - {message}\n{exc_info}',
            'style': '{',
        },
        # Для security.log
        'security': {
            'format': '{asctime} - {levelname} - {module} - {message}',
            'style': '{',
        },
    },

    # Фильтры
    'filters': {
        'require_debug_true': {
            '()': RequireDebugTrue,
        },
        'require_debug_false': {
            '()': RequireDebugFalse,
        },
    },

    # Обработчики (куда отправляем логи)
    'handlers': {
        # Консоль
        'console': {
            'class': 'logging.StreamHandler',
            'filters': ['require_debug_true'],
            'formatter': 'console',
        },
        'console_warning': {
            'class': 'logging.StreamHandler',
            'filters': ['require_debug_true'],
            'formatter': 'console_warning',
            'level': 'WARNING',
        },
        # Файл general.log
        'general_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'general.log'),
            'filters': ['require_debug_false'],
            'formatter': 'general',
            'level': 'INFO',
        },
        # Файл errors.log (только для определенных логгеров)
        'errors_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'errors.log'),
            'formatter': 'error',
            'level': 'ERROR',
        },
        # Файл security.log
        'security_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOG_DIR, 'security.log'),
            'formatter': 'security',
            'level': 'INFO',
        },
        # Email для ошибок
        'mail_admins': {
            'class': 'django.utils.log.AdminEmailHandler',
            'filters': ['require_debug_false'],
            'level': 'ERROR',
            'include_html': False,
        },
    },

    # Логгеры (источники сообщений)
    'loggers': {
        # Основной логгер django
        'django': {
            'handlers': ['console', 'console_warning', 'general_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Логгер django.request
        'django.request': {
            'handlers': ['errors_file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Логгер django.server
        'django.server': {
            'handlers': ['errors_file', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Логгер django.template
        'django.template': {
            'handlers': ['errors_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Логгер django.db.backends
        'django.db.backends': {
            'handlers': ['errors_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Логгер django.security
        'django.security': {
            'handlers': ['security_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Настройка отправки почты для администраторов (для пункта 5)
ADMINS = [
    ('Admin', 'mnhklee@yandex.ru'),
]

# Убедитесь, что email настроен для отправки ошибок
if not DEBUG:
    SERVER_EMAIL = 'mnhklee@yandex.ru'